apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sftp-distributor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/bengkelgawai/gitops'
    path: .
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: sftp-distributor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
