apiVersion: v1
kind: ConfigMap
metadata:
  name: quotes-html
  namespace: inspiring-quotes-web
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Inspiring Quotes</title>
      <style>
        body { font-family: Arial, sans-serif; background: #f9f9f9; color: #333; margin: 2em; }
        h1 { color: #2c3e50; }
        ul { list-style: none; padding: 0; }
        li { margin-bottom: 1em; padding: 1em; background: #fff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
      </style>
    </head>
    <body>
      <h1>20 Inspiring Quotes</h1>
      <ul>
        <li>"The best way to get started is to quit talking and begin doing." – Walt Disney</li>
        <li>"Don’t let yesterday take up too much of today." – Will Rogers</li>
        <li>"It’s not whether you get knocked down, it’s whether you get up." – Vince Lombardi</li>
        <li>"If you are working on something exciting, it will keep you motivated." – Steve Jobs</li>
        <li>"Success is not in what you have, but who you are." – Bo Bennett</li>
        <li>"The harder you work for something, the greater you’ll feel when you achieve it."</li>
        <li>"Dream bigger. Do bigger."</li>
        <li>"Don’t watch the clock; do what it does. Keep going." – Sam Levenson</li>
        <li>"Great things never come from comfort zones."</li>
        <li>"Push yourself, because no one else is going to do it for you."</li>
        <li>"Success doesn’t just find you. You have to go out and get it."</li>
        <li>"The only limit to our realization of tomorrow will be our doubts of today." – Franklin D. Roosevelt</li>
        <li>"Do something today that your future self will thank you for."</li>
        <li>"Little things make big days."</li>
        <li>"It’s going to be hard, but hard does not mean impossible."</li>
        <li>"Don’t wait for opportunity. Create it."</li>
        <li>"Sometimes we’re tested not to show our weaknesses, but to discover our strengths."</li>
        <li>"The key to success is to focus on goals, not obstacles."</li>
        <li>"Believe you can and you’re halfway there." – Theodore Roosevelt</li>
        <li>"Your limitation—it’s only your imagination."</li>
      </ul>
    </body>
    </html>
