apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspiring-quotes-web
  namespace: inspiring-quotes-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inspiring-quotes-web
  template:
    metadata:
      labels:
        app: inspiring-quotes-web
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: quotes-html
