apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    chart: traefik
    targetRevision: 28.1.0 # Use latest stable version or specify as needed
    helm:
      values: |
        # Custom values can be added here
        service:
          type: NodePort
        ingressClass:
          enabled: true
          isDefaultClass: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
